spring.pms.datasource.driverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.pms.datasource.jdbc-url=jdbc:log4jdbc:oracle:thin:@127.0.0.1:1521:xe
spring.pms.datasource.username=pms_user
spring.pms.datasource.password=1234
spring.pms.datasource.mapper-locations=classpath:/mybatis/mapper/**/*.xml

spring.common.datasource.mybatis-config=classpath:/mybatis/sql-mapper-config.xml